spring:
  datasource:
    url: jdbc:mysql:///tws
    username: root  #写自己的数据库用户名
    password: 686868  #写自己的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #Mapper映射文件路径
  type-aliases-package: com.sa.tws.domain #别名

server:
  port: 8090